[package]
name = "rnr-network"
version = "0.1.0"
edition = "2024"

[dependencies]
rnr-core = { path = "../rnr-core" }
rnr-datamodel = { path = "../rnr-datamodel" }
tokio = { version = "1.0", features = ["net", "sync", "time"] }
